name:                doctest-samples

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - doctest

tests:
  doctests:
    source-dirs: doctests
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
