_definitions:

  _top-level:
    - &doctest-extensions |
        -XAllowAmbiguousTypes
        -XApplicativeDo
        -XLambdaCase

  _utils:
    - &lib-common
        source-dirs: src
        verbatim:
          x-docspec-options: *doctest-extensions

name:                doctest-samples

dependencies:
- base >= 4.7 && < 5

library:
  <<: *lib-common

  dependencies:
    - aeson

tests:

  doctests:
    source-dirs: doctests
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
