name:                doctest-samples

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
    - aeson
  x-docspec-extra-packages: aeson

tests:
  docspecs:
    source-dirs: docspecs
    main: Main.hs

  doctests:
    source-dirs: doctests
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
