
<<: !include "definitions.yaml"

name:                doctest-samples

dependencies:
- base >= 4.7 && < 5

library:
  <<: *lib-common

  dependencies:
    - aeson

tests:
  docspecs:
    source-dirs: docspecs
    main: Main.hs

  doctests:
    source-dirs: doctests
    main: Main.hs
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - doctest
